### ISSUE TITLE
Unexpected EOF error on match with Examples: table

### ISSUE THREAD

**Issue by mdiskin** [karatelabs/karate-intellij-plugin#1]
<img width="1021" alt="Screen Shot 2022-06-02 at 9 17 47 AM" src="https://user-images.githubusercontent.com/505566/171638039-f917788c-f6ac-427d-944d-a0f08e668f98.png">

[Checked syntax with example](https://github.com/karatelabs/karate/blob/master/karate-demo/src/test/java/demo/outline/examples.feature)

**Comment by ptrthomas** [comment]
@mdiskin thanks ! we'll look into this

**Comment by ptrthomas** [comment]
@mdiskin it is a case where the examples may be out of date: https://github.com/karatelabs/karate#scenario-outline-enhancements

in newer versions of karate the angle-brackets are not required, `responseText` will be a valid variable

**Comment by mdiskin** [comment]
Thanks @ptrthomas removing those did get rid of the error but it also removes the usage highlights while also bring the unused columns checks into play. Apologies if it's again me not reading the manual :-)

Some related comments/questions:

- Given your initial feedback looks like it could be a feature to support/refactor older feature files (let me know if you want a separate issue created?)
- The suggest/autocomplete doesn't seem to today pull out those examples column which would be great if it could (again can create a separate issue if needed)
- I'd also would benefit the read(..)  added hyperlinks to open those in the ide and also catch if they are not found as errors.

![Screen Shot 2022-06-03 at 8 18 39 AM](https://user-images.githubusercontent.com/505566/171852473-84d8bcc4-aac1-452c-aa84-e899573ef0db.png)

**Comment by ptrthomas** [comment]
all your suggestions are valid, please keep the feedback coming. for now we will keep this ticket open and use this thread as a reference.

* yes the unused table column warning is wrong we will suppress it
* injecting the column as a JS variable is a great idea, we'll look into that
* we already have a roadmap item to validate `read()` and navigate if the file exists
* refactoring hint for old `<foo>` style is a good idea as well

**Comment by ptrthomas** [comment]
@mdiskin a new version is available that should suppress warnings for un-used columns, we will keep this open to track the other improvements

**Comment by ptrthomas** [comment]
closing this for now, as you offered, it would be great if you can open new single issues and indicate how much of a priority it is for you
