### ISSUE TITLE
After uninstalling plugin, unable to run feature files since Cucumber scenario file type pattern not restored

### ISSUE THREAD

**Issue by ericdriggs** [karatelabs/karate-intellij-plugin#13]
In order to be able to run scenarios from intellij after uninstalling plugin, users need to manually add to Editor->File Types->Cucumber Scenario->File name patters: *.feature

**Comment by ptrthomas** [comment]
this is unfortunately an issue on the jetbrains side, there is an issue opened already: https://youtrack.jetbrains.com/issue/IDEA-297533

**Comment by ptrthomas** [comment]
To save others an extra click, here is the workaround / resolution:

> *.feature is not assigned to any of the plugins. Users have to manually reassign the extension at Preferences > Editor > File types > Cucumber > File patterns

**Comment by ptrthomas** [comment]
closing this as this is actually an IntelliJ limitation. there have been requests for customizing file-type associations per-project for a long time.https://youtrack.jetbrains.com/issue/IDEABKL-6335
