### ISSUE TITLE
JSON variables defined using the "json" type marker are not given syntax highlighting

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#14]
This will provide you with a nice looking color scheme, with keys and values highlighted in different colors, etc: 
` * def test1 = { key: "value" }`
...whereas this will not -- it will just show as plain, unhighlighted text: 
` * json test2 = { key: "value" }`

**Comment by ptrthomas** [comment]
@staffier I think this can be improved. just one thing the "intent" of the `json` keyword is to convert something that may be a string into JSON etc. so it can be that the RHS is not JSON and can even be XML.

I am ok to color it if it "looks" like valid JSON and it starts with a `{` or `[` character.

**Comment by staffier** [comment]
Yeah, I had the same thing in mind.  I figured I'd bring it up because folks I work with tend to, out of habit, use `json` to define JSON variables, even if the right hand side is already JSON.

**Comment by jansorg** [comment]
The next update will have support for `* json ...` and `* xml ...`.
