### ISSUE TITLE
Feature request: improved code completion

### ISSUE THREAD

**Issue by ericdriggs** [karatelabs/karate-intellij-plugin#16]

**Comment by ptrthomas** [comment]
to add context here, the first priority is to autocomplete file names when using `read('some.feature')` and also support the `classpath:` prefix etc

**Comment by ptrthomas** [comment]
@ericdriggs let me know if the above comment is correct or if it is the ask in #15 - any specific examples would help prioritize

**Comment by ericdriggs** [comment]
Fair question. Topic was generic.
Will close until I have specific example
