### ISSUE TITLE
Feature request: recognize variables which are defined in same feature file

### ISSUE THREAD

**Issue by ericdriggs** [karatelabs/karate-intellij-plugin#17]
Currently marked as not defined

**Comment by ptrthomas** [comment]
can you provide an example ? is this for JS.

**Comment by speedofdark** [comment]
![Screen Shot 2022-10-06 at 14 52 45](https://user-images.githubusercontent.com/33673687/194425820-340bc0f9-e6b0-4140-9334-cbea18f0013a.png)

**Comment by ptrthomas** [comment]
the re-written plugin unifies the karate and js parts: https://github.com/karatelabs/karate-intellij-plugin/wiki/V2-Refactor-2024

going forward we will improve the language support (e.g. references, jump to declaration) but right now at least you don't get the annoying warning any more
