### ISSUE TITLE
JsonPath shortcut form expressions marked as syntax errors

### ISSUE THREAD

**Issue by keithdtyler** [karatelabs/karate-intellij-plugin#18]
According to manual, the JsonPath expression 
`get cat.kittens[*].id`
can also be done as
`get cat $.kittens[*].id`
and also can be done in a "short cut" form of
`$cat.kittens[*].id`

However, the second and third forms are flagged as syntax errors with the tooltip:
`'(', '.', '..', <*> or '[' expected` for the first case
`'.', '..', <*> or '[' expected, got 'cat'` for the second case

The statements all work properly when run, but those two are flagged as errors. Seems to have to do with mis-parsing of the `$` character.

![image](https://user-images.githubusercontent.com/800942/195464246-9564621d-7ebe-49d9-9253-ef26307cb8a7.png)

**Comment by jansorg** [comment]
Fixed for the next update.
