### ISSUE TITLE
Error highlighting appears incorrect

### ISSUE THREAD

**Issue by edwardsph** [karatelabs/karate-intellij-plugin#2]
The first screenshot below is from Intellij Ultimate and suggests there are various issues with my test. The second screenshot shows the problems being reported. I assume they are coming from the Karate plugin and if so, they are incorrect. I uninstalled the Karate plugin and associated *.feature with cucumber an the problems go away so it does seem to be the Karate plugin.

![Screenshot 2022-06-06 at 10 17 17](https://user-images.githubusercontent.com/9445771/172149402-7aa4ab21-e8b1-4e28-83ef-cab681980cb5.png)
![Screenshot 2022-06-06 at 12 11 17](https://user-images.githubusercontent.com/9445771/172150046-5bfb4526-bf20-482a-8c44-2569ae738135.png)

**Comment by ptrthomas** [comment]
we have added `response` and `responseStatus` as a built in variable to the latest update. some JS warnings cannot be suppressed especially those that are custom variables, this is something we will look at in the future. please open new issues and indicate how important you feel it is to be fixed
