### ISSUE TITLE
Incompatible with 2022.3 ("requires IDE build 222.* or earlier")

### ISSUE THREAD

**Issue by TaylorSMarks** [karatelabs/karate-intellij-plugin#22]
How promptly can this be fixed? I wasn't under the impression that this IntelliJ update should break anything.

**Comment by ptrthomas** [comment]
we'll update here as soon as it is available on the marketplace which should be within a day

**Comment by ptrthomas** [comment]
@TaylorSMarks while we wait for a JetBrains marketplace release, please download the ZIP from here: https://github.com/karatelabs/karate-intellij-plugin/releases/tag/v1.6.0

dragging and dropping it onto an open instance of IntelliJ will install it

**Comment by ptrthomas** [comment]
update: it is now available on the JetBrains marketplace: https://plugins.jetbrains.com/plugin/19232-karate/versions/stable/262620

**Comment by d-mh** [comment]
@ptrthomas have you seen any problems related to IDEA version 2022.3.2 - plugin is installed, but its not fully functional - looks like syntax coloring is working, but no code completion, etc. 

Plugin version: 1.6.0.214
IntelliJ IDEA version: 2022.3.2 
Runtime version: 17.0.5

Enabled plugins: Gherkin, Cucumber for Java
Thanks for any help!

**Comment by ptrthomas** [comment]
@d-mh code completion, debug and (postman-import coming within a week) require a paid upgrade. if you upgrade and still see these issues, please let us know
