### ISSUE TITLE
Errors generated after placeholder variables in angle brackets

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#24]
Depending on how they're used, placeholder variables that are populated based on Examples table entries, and enclosed in angle brackets, generate various errors.  The tests run fine, either way, though. 

For instance, this will generate a `, or ) expected` error: 
```
  Scenario Outline: 
    * def testing = read(<test>)
    
    Examples:
      | test      |
      | 'my.json' |
```

...and this will generate an `Unexpected end of file` error: 
```
  Scenario Outline: 
    * def testing = <test>
    
    Examples:
      | test |
      | 123  |
```

**Comment by ptrthomas** [comment]
we'll check if this is easily fixable. that said, we no longer recommend the `<>` notation - except in the `Scenario` name - because the table data is turned into "proper" karate variables

```cucumber
Scenario Outline: 
    * def testing = read(test)
    
    Examples:
      | test      |
      | my.json |
```

**Comment by ptrthomas** [comment]
fixed in the new version: https://github.com/karatelabs/karate-intellij-plugin/wiki/V2-Refactor-2024
