### ISSUE TITLE
Karate IntelliJ Plugin doesn't support code collapsing/folding

### ISSUE THREAD

**Issue by PBMax02** [karatelabs/karate-intellij-plugin#27]
I just updated to Karate 1.4.0 from 1.3.1 and require the use of the IntelliJ plugin.  Some what I thought was basic functionality is missing.  One of those basic feature is being able to collapse code using the IDE folding options.  I use that to quickly scan a file to review scenarios to find a case I'm looking for etc.

Is that supposed to be supporting in this plugin?  I know that seems like a small issue but it's something that I use often and you only know how much you use it when it goes away.

Here is my feature file when I'm using the Karate 1.7.4.325 plugin:
![image](https://user-images.githubusercontent.com/68280714/235147666-a1c4cff7-6e58-4919-aa55-b08ee8d16238.png)

Here is my feature file when I use the Gherkin plugin:
![image](https://user-images.githubusercontent.com/68280714/235161487-f45f6b30-27a2-4fa1-9d95-5e1e89e26b1f.png)

**Comment by ptrthomas** [comment]
@PBMax02 code folding for the karate plugin is a premium feature, please do consider upgrading to get this along with the ability to debug karate tests in IntelliJ and more: https://plugins.jetbrains.com/plugin/19232-karate

**Comment by PBMax02** [comment]
Thanks for the response.  It wasn't clear from the plugin page that this was a premium feature. You should look at updating the info to make it clear that this is another benefit of the plugin that has been integral to my testing.

**Comment by ptrthomas** [comment]
@PBMax02 thanks for the feedback, we will do that
