### ISSUE TITLE
Karate IntelliJ plugin parsing breaks after using karate.jsonPath in match statement

### ISSUE THREAD

**Issue by PBMax02** [karatelabs/karate-intellij-plugin#28]
I created the scenario below to illustrate how parsing breaks after having a karate.jsonPath command in my match statement.  These are tests that parsed fine before the use of the plugin when moving to Karate 1.4.0.

This makes it so that tests cannot be run individually after the command and would require us to update lots of tests to make the parser work correctly.  I have some feature files where half the file is just grey text because it failed parsing the scenarios half way through.

Using Karate Plugin 1.7.4.325

![image](https://user-images.githubusercontent.com/68280714/235164632-53f912a9-d86e-4724-8914-18f0ee93c6e3.png)

**Comment by jansorg** [comment]
This should be fixed with the next update.
