### ISSUE TITLE
Variable references in JSON objects are being flagged with errors

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#3]
This JSON blob: 

    * def someVar =
      """
      {
        "status": "status",
        "expiryDate": {
          "month": #(~~expiryMonth()),  <--- these two lines are the problem
          "year": #(~~expiryYear(2)).       <---
        }
      }
      """

... is getting flagged with the following errors: 
value expected, got '#' 
JSON standard does not allow such tokens
':' expected, got ','

**Comment by ptrthomas** [comment]
@staffier I'm treating this as a won't fix, to be valid JSON, enclose the `#()` parts in quotes
