### ISSUE TITLE
Feature request: allow debug breakpoints in java code using free plugin

### ISSUE THREAD

**Issue by ericdriggs** [karatelabs/karate-intellij-plugin#30]
Currently only the paid plugin allows any debugging/breakpoints.

The cucumber java plugin allows setting java breakpoints, so imo it's currently better than the free plugin.

Current behavior:
* able to set breakpoints in feature files
* debug feature fails with error that debugger support is a paid feature

Recommended behavior for free version:
* setting breakpoints in feature files should fail with error that debugging support is a paid feature
* running debug should ignore any feature file breakpoints

**Comment by ptrthomas** [comment]
you can always write a java "runner" as an entry point and init a java debug session that way

**Comment by ptrthomas** [comment]
closing as a won't fix
