### ISSUE TITLE
Scenario fails to run when starting line changes

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#32]
Steps:
1. Using scenario file 1 below, run the 2nd scenario.
   - This can be done with keyboard shortcuts, using the gutter shortcut or by right-clicking on the scenario and selecting "Run...".
2. Scenario passes.
3. Change the file in any way such that the 2nd scenario is on a different line number, higher or lower.
4. ACTUAL: Scenario will not be found, and thus the test shows up as "Terminated".
   - EXPECTED: Scenario would be run by name, and thus would be found regardless of line number, as long as scenario name was unchanged.

Failure variation:
1. Run first test as normal.
2. Alter the file in such a way that the IntelliJ auto-formatter will alter the file.
    - Example: add 3 blank lines in between 1st and 2nd scenario.
3. Run the 2nd scenario by gutter or keyboard shortcut or right-click.
4. IntelliJ Karate Plugin is triggered to run based on current file conditions.
5. When the Run window receives focus, the auto-formatter is triggered.
6. The 2nd scenario moves up.
7. ACTUAL: Scenario will not be found, and thus the test shows up as "Terminated".
   - EXPECTED: Scenario would be run by name, and thus would be found regardless of line number, as long as scenario name was unchanged.

```cucumber
Feature: A simple Karate test that always passes

  Scenario: Dummy Test

    * def foo = 1234
    * def bar = 1234
    * match foo == bar
# variations on this empty space will cause the issue
  Scenario: Line changing scenario # this line number must change

    * def foo = 1234
    * def bar = 1234
    * match foo == bar
```

**Comment by ptrthomas** [comment]
should be not an issue in the [new EA version](https://github.com/karatelabs/karate-intellij-plugin/wiki/V2-Refactor-2024)

**Comment by arnaldop** [comment]
@ptrthomas, this is back to being a problem. I don't think it can be resolved as long as the plugin defines the Run Configuration with line numbers (see 2nd image). It feels to me that something more sophisticated is needed, such as searching for "^\s*Scenario:(.*)\s*$".

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/9d69e0a3-e114-4160-b2f3-e9c17f05e9d2)

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/dc6ec60d-b73a-49c8-a9a8-0cc9ff088a73)

**Comment by ptrthomas** [comment]
@arnaldop will look into this - but do you have some setting where intellij auto-formats the file on save ? I was never able to replicate this

**Comment by arnaldop** [comment]
@ptrthomas, for this scenario, I just manually reformatted the file repeatedly (keyboard shortcut multiple times). But it feels to me that if I make changes to the file and IntelliJ reformats it in save, that the same thing would happen. I'll test it shortly and report back.

**Comment by arnaldop** [comment]
@ptrthomas, ok, I understand your question now.

So considering my original example, when I run the 2nd Scenario, the plugin creates a Run Configuration pointing to line 9 (assuming the file reads exactly as above).

So now assume I add 5 more lines at the tail end of the 1st Scenario. If nothing else changed, then my 2nd Scenario now starts at line 14 (9+5). So if I hit Shift+F10 to re-run the 2nd Scenario, the run fails because there is no Scenario starting at line 9. Line 9 is in the middle of the 1st Scenario now.

So what would need to happen is that the Run Configuration "Feature / path" line cannot contain a line number, but some other identifier of the Scenario (thus my regular expression above).

Perhaps this is a shortcoming with Karate itself, not the plugin, as I haven't found a way to do this even from the command line.

**Comment by ptrthomas** [comment]
@arnaldop okay I think the only option is to click on the gutter icon again and discard the old run config.

in the long term we could switch to using the "index" of the scenario within the feature, that should solve this problem

by the way right-clicking on a cell within `Examples` should give you the option to run a single line

**Comment by arnaldop** [comment]
@ptrthomas, was this issue logged as a new feature request ticket? Should I do that?

**Comment by ptrthomas** [comment]
@arnaldop yes you can open a new ticket
