### ISSUE TITLE
With the latest IDEA version update 2023.2, the karate run hangs even though all the scenarios have completed execution

### ISSUE THREAD

**Issue by DeepKandey** [karatelabs/karate-intellij-plugin#35]
With the latest IDEA version update 2023.2, the karate run hangs even though all the scenarios have completed execution
Because of this issue, I am unable to generate the report via the plugin run

karate plugin version - 1.7.6.353-232

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/39937316/204ad701-5262-4187-b0fe-fa19e2170202)

**Comment by ptrthomas** [comment]
@DeepKandey can you kindly provide a sample project to replicate this, ideally follow these lines: https://github.com/karatelabs/karate/wiki/How-to-Submit-an-Issue

I am also happy to get on a call and look through your project if ok with you, you can email me at peter AT karatelabs.io

**Comment by mvaldez** [comment]
Me and another developer on my team are having the same problem.  It appears the karate plugin is broken for Intellij 2023.2.

**Comment by DeepKandey** [comment]
@ptrthomas Please find the sample project - https://github.com/DeepKandey/karatePluginIssue

Please run this project on the latest IDEA version and the karate plugin version mentioned in the above issue description. 
Hope this helps.

**Comment by ptrthomas** [comment]
we are looking into this cc @jansorg there seems to be an issue resolving the working folder, and strangely only in 2023. will update here when we release a fix.

**Comment by jansorg** [comment]
I can confirm the issue in 2023.2, which changed some code we were calling to setup the working directory.
A fix is underway.

**Comment by ptrthomas** [comment]
@DeepKandey @mvaldez the new release `1.7.7.361` is now available, thanks for the feedback and your patience 🙏
