### ISSUE TITLE
Run Configurations not using environment/VM options/arguments

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#36]
Running tests using the plugin does not take any of these into account:
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/5170efbb-8dbb-4a31-9a99-cfab760bdc42)

To confirm, I expanded the full command in the Run window, and searched for the missing parameter, and it was not anywhere in the command.

```
/bin/java
-javaagent:...
-Dfile.encoding=UTF-8
-Dsun.stdout.encoding=UTF-8
-Dsun.stderr.encoding=UTF-8
-classpath JARs.jar
com.intuit.karate.Main
-H com.intuit.karate.cli.IntellijHook
/project/feature.feature:222
```

This was working at least 2-3 weeks ago.

**Comment by mvaldez** [comment]
I'm having the same problem.  The environment variables are not persisting when using the Karate intellij plugin on 2023.2.  Works fine using command line with gradle.

**Comment by ptrthomas** [comment]
this is high-priority, we are looking into it

**Comment by jansorg** [comment]
AFAIK this has the same root cause as https://github.com/karatelabs/karate-intellij-plugin/issues/35

**Comment by ptrthomas** [comment]
@arnaldop @mvaldez the new release `1.7.7.361` is now available, thanks for the feedback and your patience 🙏
