### ISSUE TITLE
karate.write throws FileNotFoundException

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#37]
Might be related to https://github.com/karatelabs/karate-intellij-plugin/issues/36.

```
01: karate.write(responseBytes, 'exports/' + filename)
<<<<
org.graalvm.polyglot.PolyglotException: java.io.FileNotFoundException: target/exports/export.xlsx (No such file or directory)
- com.intuit.karate.FileUtils.writeToFile(FileUtils.java:187)
- com.intuit.karate.core.ScenarioBridge.write(ScenarioBridge.java:1135)
- <js>.:program(Unnamed:1)
```

Again, this was working 2-3 weeks ago.

**Comment by ptrthomas** [comment]
@arnaldop we are looking into it cc @jansorg - I just wanted to be sure this is not related to https://github.com/karatelabs/karate-intellij-plugin/issues/31 - in other words, if you set the working-dir correctly will your problem be solved

if not, a way to replicate this problem will really help

**Comment by ptrthomas** [comment]
@arnaldop please ignore my post above, I think this is the same issue with run configurations not being passed cleanly to the karate process in the 2023 version of the plugin. we are able to replicate this

**Comment by ptrthomas** [comment]
@arnaldop the new release `1.7.7.361` is now available, thanks for the feedback and your patience 🙏
