### ISSUE TITLE
Plugin is using non-existent Karate 1.5.0-SNAPSHOT instead of the version defined in pom.xml

### ISSUE THREAD

**Issue by pavinil** [karatelabs/karate-intellij-plugin#38]
Intellij version: 2023.2 Build #IC-232.8660.185, built on July 26, 2023
Plugin version: 1.7.7.361-232

Steps to reproduce:
1. Create a new karate project using https://github.com/karatelabs/karate#quickstart command
2. Navigate to examples/users/users.feature and click the Play button next to the first scenario
3. Now, change the karate version in pom.xml to 0.9.6 and add karate-apache dependency
4. Repeat step 2

Expected:
The plugin should use karate 0.9.6 to run the test

Actual:
The plugin uses Karate 1.5.0 - SNAPSHOT

**Comment by ptrthomas** [comment]
@pavinil sorry, karate 0.9.6 is a very very old version and is no longer supported. the intellij plugin expects new versions. please upgrade
