### ISSUE TITLE
Cannot run tests within a folder

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#39]
Steps to reproduce:
1. Right-click on folder containing feature files.
![Screenshot 2023-08-11 at 2 47 56 PM](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/a3e18b71-dd90-4be2-8bf3-08b5239ea555)
2. Select "Run 'Tests in 'commission''".
![Screenshot 2023-08-11 at 2 48 55 PM](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/999f9de7-2cf6-457b-91f3-a2256df63034)
3. Run dialog shows "No tests were found."
![Screenshot 2023-08-11 at 2 49 27 PM](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/7c97fd05-a730-41f8-a39b-666b40637022)

All files are runnable. None are marked with `@ignore`.

**Comment by ptrthomas** [comment]
<img width="502" alt="image" src="https://github.com/karatelabs/karate-intellij-plugin/assets/915480/17814bf3-4285-4860-99a9-df16be81e753">

fixed in new version: https://github.com/karatelabs/karate-intellij-plugin/wiki/V2-Refactor-2024
