### ISSUE TITLE
Tests run from a Java class open in target

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#40]
Steps:
1. Create a directory.
2. Add a Karate Feature file.
3. Add a Java class that runs all Features in the current directory.
4. From the Run Window, double-click on an individual Scenario.

Expected:
- The IDE would open the Feature file from the `src` directory.

Actual:
- The IDE opens the Feature file from the `target` directory.
- This means that any changes we make to it will be silently overwritten.

Seems loosely related to https://github.com/karatelabs/karate-intellij-plugin/issues/39.

**Comment by ptrthomas** [comment]
should not happen in Karate 1.5.0.RC3 onwards. 

going forward, recommended way of running tests is via Karate run configurations in IntelliJ, there is a new EA version available here: https://github.com/karatelabs/karate-intellij-plugin/wiki/V2-Refactor-2024

java runners will not communicate results back to IntelliJ, but the Karate HTML reports can be used instead.
