### ISSUE TITLE
IntelliJ: JavaScript-style outline variables are not interpolated in scenario names

### ISSUE THREAD

**Issue by petrandreev** [karatelabs/karate-intellij-plugin#41]
In IntelliJ IDEA, Build #IC-232.9921.47, built on September 12, 2023
with Karate (Freemium) plugin, Version 1.7.7.361-232:

while running tests in `karate-core/src/test/java/com/intuit/karate/core/parser/test-outline-name-js.feature`
the JS variable names are not interpolated and the cog wheels suggest tests to infinitely run, but they all are completed:
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/5670574/e65cd5a1-f570-41f4-a325-b6ac46d5072a)

Karate reports show proper JS-expressions interpolation though:
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/5670574/e3d608fb-8edf-4c7b-8bd9-455ee2727092)

**Comment by ptrthomas** [comment]
@petrandreev interesting. the intellij log parsing system doesn't seem to like back-ticks and `${}`. 

the below test works fine, but the moment you add one of the above, you see the problem

```cucumber
Feature:

Scenario Outline: name is
* def name = name
* match name == "#? _ == 'Bob' || _ == 'Nyan'"

Examples:
| name   | age | title                     |
| Bob    | 10  | name is Bob and age is 10 |
| Nyan   | 5   | name is Nyan and age is 5 |
```

**Comment by petrandreev** [comment]
well the issue is not 100% related to Intellij, since I can see the similar logs in the gradle runs, like: 
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/5670574/fa5c5027-0829-4823-ba44-12d388b04ecf)

**Comment by ptrthomas** [comment]
@petrandreev then please follow this process so we can fix this in the core project: https://github.com/karatelabs/karate/wiki/How-to-Submit-an-Issue

**Comment by petrandreev** [comment]
Thanks for response, I'm sure you will find the paid time to file the issue, following the mentioned `process`. Good luck.

**Comment by ptrthomas** [comment]
fixed and in early access here: https://github.com/karatelabs/karate-intellij-plugin/wiki/V2-Refactor-2024
