### ISSUE TITLE
Intjplus plug-in subscription issue

### ISSUE THREAD

**Issue by HusniR** [karatelabs/karate-intellij-plugin#42]
My Intjplus plug-in status is subscribe but incomplete. How do i fix that?

**Comment by ptrthomas** [comment]
@HusniR can you drop us an email to info AT karatelabs.io or use our contact form: https://www.karatelabs.io/contact-us - once we know the email you used to sign-in - we should be able to reset your subscription status. we will also check how to avoid this issue.
