### ISSUE TITLE
Should be able to stop at Karate break points even when entry point was Java runner

### ISSUE THREAD

**Issue by ptrthomas** [karatelabs/karate-intellij-plugin#44]
as reported here: https://stackoverflow.com/a/76752898/143475

**Comment by IamMashed** [comment]
Hi @ptrthomas 
I am the one requesting this feature in stackoverflow. 
Is karate open source? perhaps I can work on this enhancement myself?

**Comment by ptrthomas** [comment]
thanks @IamMashed - the core of karate is open source and over here: https://github.com/karatelabs/karate

this tracker is for the IntelliJ IDE plugin which is not open-source

**Comment by ptrthomas** [comment]
fix available for early access here: https://github.com/karatelabs/karate-intellij-plugin/wiki/V2-Refactor-2024
