### ISSUE TITLE
v2.0.0 does not accept command line arguments

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#45]
As stated [here](https://github.com/karatelabs/karate-intellij-plugin/issues/36), I rely on command line arguments to enable/disable logging.

With the new test configuration, there is no place for command line arguments:
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/dc7086ac-c7ae-4682-b105-60111f1a1817)

This is the result of the test run:
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/9ebe95a2-1840-4063-a173-8c923c9f72b4)

For reference, this is the logback configuration I use:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

    <logger name="com.intuit.karate" level="DEBUG"/>

    <if condition='property("consoleOutput").equals("true")'>
        <then>
            <include
                    resource="org/springframework/boot/logging/logback/console-appender.xml"/>

            <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
                <encoder>
                    <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
                    </pattern>
                </encoder>
            </appender>

            <root level="INFO">
                <appender-ref ref="CONSOLE"/>
            </root>
        </then>
        <else>
            <property name="LOG_FILE" value="/var/log/agencycomp/tests.log"/>
            <include
                    resource="org/springframework/boot/logging/logback/file-appender.xml"/>

            <root level="INFO">
                <appender-ref ref="FILE"/>
            </root>
        </else>
    </if>
</configuration>
```

**Comment by ptrthomas** [comment]
@arnaldop this feedback is much appreciated, have added this - and screenshot below. thanks for the tip on logback config - I had no idea this was possible and will refer others here who need it

we will release the final plugin early next week, but will continue to quickly turn around any issues you face

<img width="703" alt="image" src="https://github.com/karatelabs/karate-intellij-plugin/assets/915480/93a03888-4320-4645-87a8-b61cb25fc2f6">

**Comment by arnaldop** [comment]
@ptrthomas, FYI, the ability to make log config files "smart" requires Janino. It's all explained [here](https://logback.qos.ch/setup.html#janino).

**Comment by ptrthomas** [comment]
@arnaldop ah thanks.

btw JVM params in the run config should be working in the latest EA release

**Comment by arnaldop** [comment]
@ptrthomas, I haven't tested this yet, but this is what the dialog does right now. I didn't even realize that I could type for those 2 properties!
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/8f2d40bc-c3d2-4988-be09-5241e2a712ec)

**Comment by arnaldop** [comment]
@ptrthomas, just tested the JVM parameters (using `-DconsoleOutput=true`) and it worked perfectly. Thx
