### ISSUE TITLE
Formatting is flattening JSON

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#46]
When a Karate feature file gets formatted, all JSON is flattened. See examples below.
Unfortunately (well, fortunately, I guess), all of my projects rely on auto-formatting to keep things consistent.
Thus, any time I change a feature file, my JSON gets flattened and I can't undo it without turning off auto-format in the IDE settings.
I think this must be a Karate issue. This was not the behavior prior to the introduction of the Pro tier. Also, for a short while, I did not use the Karate plugin. I only started experiencing this with this version of the plugin. It is possible that the last released version works fine in this regard.

Before
```json
    * def testData =
      """
        {
          agent: {
            lastName: '#(randomAlphabetic(5))',
            firstName: '#(randomAlphabetic(5))'
          },
          carrier: {
            name: 'Test Carrier'
          },
          individual: {
            lastName: '#("D" + randomAlphabetic(5))',
            firstName: '#("E" + randomAlphabetic(5))'
          },
          file: {
            name: 'payload.csv',
            type: 'csv'
          },
          importMap: {
            name: '#("Map " + randomAlphabetic(7))',
            file: 'payload.csv',
            numberOfSheets: 1,
            dataTabIndex: 1,
            firstDataRow: 2,
            sheetNames: null,
            autoUpdateEffectiveDate: true,
            fileColumnsFileName: 'field-mappings-minimum-fields.json'
          },
          policy: {
            policyNumber: 'P1',
            compPlanType: 'MA_PDP',
            effectiveDate: '2022-01-01',
            mapdpDetails: { enrollmentType: 'NEW' }
          },
          compPlan: {
            name: '#(randomAlphanumeric(8))',
            type: 'MA_PDP',
            schedule: [
              {
                beginYear: 1,
                endYear: 1,
                fee: 573,
                frequency: 'ONETIME',
              },
              {
                beginYear: 2,
                fee: 23.92,
                frequency: 'MONTHLY',
              }
            ]
          }
        }
      """
```

After
```json
    * def testData =
      """
      {
      agent: {
      lastName: '#(randomAlphabetic(5))',
      firstName: '#(randomAlphabetic(5))'
      },
      carrier: {
      name: 'Test Carrier'
      },
      individual: {
      lastName: '#("D" + randomAlphabetic(5))',
      firstName: '#("E" + randomAlphabetic(5))'
      },
      file: {
      name: 'payload.csv',
      type: 'csv'
      },
      importMap: {
      name: '#("Map " + randomAlphabetic(7))',
      file: 'payload.csv',
      numberOfSheets: 1,
      dataTabIndex: 1,
      firstDataRow: 2,
      sheetNames: null,
      autoUpdateEffectiveDate: true,
      fileColumnsFileName: 'field-mappings-minimum-fields.json'
      },
      policy: {
      policyNumber: 'P1',
      compPlanType: 'PERCENTAGE_OF_PREMIUM',
      netPremium: 176.23,
      mode: 'MONTHLY',
      effectiveDate: '#(dateFirstOfYear(-1))',
      },
      otherComp: {
      compPlanType: 'PERCENTAGE_OF_PREMIUM',
      effectiveDate: '#(dateFirstOfYear(-1))',
      },
      compPlan: {
      name: '#(randomAlphanumeric(8))',
      type: 'PERCENTAGE_OF_PREMIUM',
      schedule: [
      {
      beginYear: 1,
      endYear: 1,
      commissionRate: 1,
      },
      {
      beginYear: 2,
      commissionRate: 0.010,
      }
      ]
      }
      }
      """
```

**Comment by ptrthomas** [comment]
@arnaldop thanks this will also be fixed in the release version.

**Comment by ptrthomas** [comment]
@arnaldop while we wait for the official release, please see if this is fixed in the latest EA version: https://github.com/karatelabs/karate-intellij-plugin/releases/tag/v2.0.0.EAP

**Comment by arnaldop** [comment]
Yes, @ptrthomas, formatting is fixed! Thanks!

**Comment by arnaldop** [comment]
@ptrthomas, weirdly enough, it seems worse now. When duplicating a block of code, IntelliJ formats the new code automatically. This is the outcome. Line 285 is the end of the source material. Line 286 is the beginning of the output. Everything got more flattened than the original example above.

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/0d2613a9-85bd-4516-b2df-f2872776bcae)

**Comment by ptrthomas** [comment]
@arnaldop can you make sure that the JSON is well formed. it shows all white which suggests there may be a comma or curly brace out of place. which is something we will fix, because we can't have one error in a step break the whole file (which explains why you had the other structure problem)

if you still see a weird error when cutting and pasting, do try and provide a sample to simulate. also suggestions on what more could be gracefully handled welcome

**Comment by arnaldop** [comment]
@ptrthomas, below is a representative code snippet.
Interestingly, if I grab lines 65-72, which are interpreted to be valid (no red underline), and paste them just after line 40, that JSON fragment becomes invalid and formats against the margin. That's shown in the 2nd image.

I also tried to replace `set` with `def` as well as removing `set` altogether. I didn't expect that to work, and it didn't.

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/1e444349-1172-403c-9f2e-6d0f6f899583)
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/53fc7d87-72c4-46f1-9b0e-0b464d3b4e7e)

**Comment by arnaldop** [comment]
@ptrthomas, here is another weird behavior. Same file, 2 scenarios, different interpretation of the JSON.
But both of them end up flattening, and if I switch the 2 scenarios, the non-flagged one becomes flagged.
The 2nd image is of the Background. Perhaps that is the source of the issue.

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/6de88a56-c7d6-4c01-941a-0217a93f080c)

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/b1d91233-6952-4da3-bcf7-d78d10554a20)

**Comment by ptrthomas** [comment]
@arnaldop actually the `set` syntax was not handled by the parser properly which is fixed

also now the parser is improved so a syntax failure in one step won't crash the rest of the file. thanks for the feedback !
