### ISSUE TITLE
Dialog is improperly built

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#48]
Missing textbox formatting for `karate.options` and `JVM parameters`. Also, tab only adds the spaces rather than moving from one field to another.

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/c5dafbe4-9696-40df-9e0c-9bda9d45dc82)

**Comment by ptrthomas** [comment]
should be fixed in latest version: https://github.com/karatelabs/karate-intellij-plugin/releases/tag/v2.0.0.EAP
