### ISSUE TITLE
Examples table variables are causing errors when included between parenthesis 

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#5]
Something like this: 

` * karate.set('Request', '<jsonPath>', <value>)`

...is resulting in an error telling me `, or ) expected`

The placeholder `<value>` at the end is causing the problem.

**Comment by ptrthomas** [comment]
@staffier I'm treating this also as a won't fix. over time, we will discourage the use of `<>` since a proper variable with that name will always exist, refer #1
