### ISSUE TITLE
Jump to test failure

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/karate-intellij-plugin#52]
Currently, you can just from the Run (Test) Dialog to the Scenario that failed.
It would be great to jump directly to the failing line in the scenario.
Image below of 3 places where that information appears.

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/e9f34f93-decd-4fcf-9a17-99ec504c0831)

**Comment by ptrthomas** [comment]
should be fixed in latest EAP https://github.com/karatelabs/karate-intellij-plugin/releases/tag/v2.0.0.EAP

**Comment by arnaldop** [comment]
This is beautiful!!!

**Comment by arnaldop** [comment]
Happening again in some cases:
![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/c9cf31d3-1b92-4c4e-bce5-8d64fd25f159)

**Comment by ptrthomas** [comment]
we are looking into this, will release next week if possible

**Comment by ptrthomas** [comment]
@arnaldop this is also fixed in 2.0.2 available at the marketplace

**Comment by arnaldop** [comment]
@ptrthomas, how do I install from the marketplace after I installed from disk? Both are 2.0.2.

**Comment by ptrthomas** [comment]
@arnaldop just un-install the plugin and then search for it on the marketplace

**Comment by arnaldop** [comment]
@ptrthomas, reinstalled. Ran tests with Java class with method annotated with `@Karate.Test`. No links.
![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/cbd4998d-6777-4cea-8a07-4aae7c79e675)

**Comment by ptrthomas** [comment]
@arnaldop right now we can't support the Java entry point. it could be possible in the future
