### ISSUE TITLE
Running a Scenario Outline from the gutter results in the entire feature file being run

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#6]
Running the Scenario below from the gutter will print "test 1," but running the Scenario Outline will print "test 1" along with "test 2" and "test 3." 

```gherkin
Feature: 

  Scenario:
    * print 'test 1'

  Scenario Outline:
    * print 'test' + <test>

    Examples:
      | test |
      | 2    |
      | 3    |
```

**Comment by jansorg** [comment]
@ptrthomas This is a bug in the plugin, the line number isn't added on the command line. But when it's added, it's showing the same symptoms of #7
