### ISSUE TITLE
The "get" keyword is generating errors

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#9]
The following scenario will have a few things flagged in the ` * def kitnums = ` line: 
A newline or semicolon expected error after `get`
An expression expected error for `[*]`
A statement expected error for `[*]`

```gherkin
 Scenario:
   * def cat = 
  """
  {
    name: 'Billie',
    kittens: [
      { id: 23, name: 'Bob' },
      { id: 42, name: 'Wild' }
    ]
  }
  """
   * def kitnums = get cat.kittens[*].id
```

**Comment by ptrthomas** [comment]
yes this is an edge case, refer: https://github.com/karatelabs/karate#get

the complete rules for where Karate diverges from JS are here: https://github.com/karatelabs/karate/blob/v1.2.1.RC1/karate-core/src/main/java/com/intuit/karate/core/ScenarioEngine.java#L2316

**Comment by jansorg** [comment]
This is fixed for the next update.
